export const PATHS = {
  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  DEFAULT: '/',
  DASHBOARD: '/dashboard',
  PROFILE: '/profile',
  ADD_PROFILE: '/add-profile',
  HOW: '/how',
  ABOUT: '/about',
  FEATURES: '/features',
  WINNINGS: '/winnings',
  SCHEDULED_QUIZES: '/scheduled-quizes',
  ALL_COURSES: '/all_courses',
  MY_PROFILE: '/my_profile',
  MENTOR_PROFILE: '/mentor_profile',
  ASKS: '/asks',
  BANK_DETAILS: '/bank-details',
};
